"""add findings table

Revision ID: 2d66c843ef0e
Revises: da05efe02a74
Create Date: 2026-05-21 10:28:48.793882

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '2d66c843ef0e'
down_revision: str | Sequence[str] | None = 'da05efe02a74'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('check_code', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=True),
    sa.Column('subject_key', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index('ix_finding_company_year_code', ['company_id', 'period_year', 'check_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_check_code'), ['check_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_period_year'), ['period_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_subject_key'), ['subject_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_subject_key'))
        batch_op.drop_index(batch_op.f('ix_findings_status'))
        batch_op.drop_index(batch_op.f('ix_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_findings_period_year'))
        batch_op.drop_index(batch_op.f('ix_findings_company_id'))
        batch_op.drop_index(batch_op.f('ix_findings_check_code'))
        batch_op.drop_index('ix_finding_company_year_code')

    op.drop_table('findings')
    # ### end Alembic commands ###
