"""add company_year_scores table

Revision ID: 46b3bcaebbe4
Revises: de9eee546b80
Create Date: 2026-05-26 17:05:52.912154

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '46b3bcaebbe4'
down_revision: str | Sequence[str] | None = 'de9eee546b80'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_year_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=64), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_year', name='uq_company_year_score')
    )
    with op.batch_alter_table('company_year_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_year_scores_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_year_scores_period_year'), ['period_year'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_year_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_year_scores_period_year'))
        batch_op.drop_index(batch_op.f('ix_company_year_scores_company_id'))

    op.drop_table('company_year_scores')
    # ### end Alembic commands ###
