"""uom canonical + aliases

Revision ID: 599dbd931e77
Revises: 9fbf36d7f864
Create Date: 2026-05-21 14:32:05.877909

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '599dbd931e77'
down_revision: str | Sequence[str] | None = '9fbf36d7f864'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uom_canonical',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('base_factor', sa.Float(), nullable=False),
    sa.Column('name_vi', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('uom_canonical', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uom_canonical_family'), ['family'], unique=False)

    op.create_table('uom_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=False),
    sa.Column('canonical_code', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_code'], ['uom_canonical.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uom_aliases', schema=None) as batch_op:
        batch_op.create_index('ix_uom_alias_canonical', ['canonical_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_uom_aliases_alias'), ['alias'], unique=True)
        batch_op.create_index(batch_op.f('ix_uom_aliases_canonical_code'), ['canonical_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uom_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uom_aliases_canonical_code'))
        batch_op.drop_index(batch_op.f('ix_uom_aliases_alias'))
        batch_op.drop_index('ix_uom_alias_canonical')

    op.drop_table('uom_aliases')
    with op.batch_alter_table('uom_canonical', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uom_canonical_family'))

    op.drop_table('uom_canonical')
    # ### end Alembic commands ###
