"""add_check_definitions_table

Revision ID: 646b92a93768
Revises: 46b3bcaebbe4
Create Date: 2026-05-26 19:29:52.482757

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '646b92a93768'
down_revision: str | Sequence[str] | None = '46b3bcaebbe4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
