"""company.risk_score

Revision ID: 9fbf36d7f864
Revises: 2d66c843ef0e
Create Date: 2026-05-21 11:34:54.606649

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '9fbf36d7f864'
down_revision: str | Sequence[str] | None = '2d66c843ef0e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_score', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_companies_risk_score'), ['risk_score'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_risk_score'))
        batch_op.drop_column('risk_score')

    # ### end Alembic commands ###
