"""add app_settings table

Revision ID: a4d5ffcb0da7
Revises: 646b92a93768
Create Date: 2026-05-26 21:31:14.891128

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a4d5ffcb0da7'
down_revision: str | Sequence[str] | None = '646b92a93768'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
