"""initial schema: companies, bcqt (M15/M15a/M16), declaration lines

Revision ID: da05efe02a74
Revises: 
Create Date: 2026-05-21 01:38:16.171323

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'da05efe02a74'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_tax_id'), ['tax_id'], unique=False)

    op.create_table('declaration_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('declaration_no', sa.String(length=32), nullable=False),
    sa.Column('declaration_date', sa.Date(), nullable=True),
    sa.Column('customs_code', sa.String(length=8), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('item_code', sa.String(length=64), nullable=True),
    sa.Column('item_name', sa.String(length=500), nullable=True),
    sa.Column('hs_code', sa.String(length=16), nullable=True),
    sa.Column('origin', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('value_foreign', sa.Float(), nullable=True),
    sa.Column('value_total', sa.Float(), nullable=True),
    sa.Column('tax_total', sa.Float(), nullable=True),
    sa.Column('partner', sa.String(length=255), nullable=True),
    sa.Column('invoice_no', sa.String(length=64), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('declaration_lines', schema=None) as batch_op:
        batch_op.create_index('ix_decl_company_year_code', ['company_id', 'period_year', 'item_code'], unique=False)
        batch_op.create_index('ix_decl_customs', ['company_id', 'period_year', 'customs_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_declaration_lines_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_declaration_lines_customs_code'), ['customs_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_declaration_lines_declaration_date'), ['declaration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_declaration_lines_declaration_no'), ['declaration_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_declaration_lines_hs_code'), ['hs_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_declaration_lines_item_code'), ['item_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_declaration_lines_period_year'), ['period_year'], unique=False)

    op.create_table('norms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('product_unit', sa.String(length=32), nullable=True),
    sa.Column('material_code', sa.String(length=64), nullable=False),
    sa.Column('material_name', sa.String(length=500), nullable=True),
    sa.Column('material_unit', sa.String(length=32), nullable=True),
    sa.Column('norm_qty', sa.Float(), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('norms', schema=None) as batch_op:
        batch_op.create_index('ix_norm_company_year_pair', ['company_id', 'period_year', 'product_code', 'material_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_norms_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_norms_material_code'), ['material_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_norms_period_year'), ['period_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_norms_product_code'), ['product_code'], unique=False)

    op.create_table('nvl_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('material_code', sa.String(length=64), nullable=False),
    sa.Column('material_name', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('opening_qty', sa.Float(), nullable=False),
    sa.Column('import_qty', sa.Float(), nullable=False),
    sa.Column('reexport_qty', sa.Float(), nullable=False),
    sa.Column('repurpose_qty', sa.Float(), nullable=False),
    sa.Column('production_out_qty', sa.Float(), nullable=False),
    sa.Column('other_out_qty', sa.Float(), nullable=False),
    sa.Column('closing_qty', sa.Float(), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nvl_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nvl_balances_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nvl_balances_material_code'), ['material_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_nvl_balances_period_year'), ['period_year'], unique=False)
        batch_op.create_index('ix_nvl_company_year_code', ['company_id', 'period_year', 'material_code'], unique=False)

    op.create_table('sp_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('product_code', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('opening_qty', sa.Float(), nullable=False),
    sa.Column('intake_qty', sa.Float(), nullable=False),
    sa.Column('repurpose_qty', sa.Float(), nullable=False),
    sa.Column('export_qty', sa.Float(), nullable=False),
    sa.Column('other_out_qty', sa.Float(), nullable=False),
    sa.Column('closing_qty', sa.Float(), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sp_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sp_balances_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sp_balances_period_year'), ['period_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_sp_balances_product_code'), ['product_code'], unique=False)
        batch_op.create_index('ix_sp_company_year_code', ['company_id', 'period_year', 'product_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sp_balances', schema=None) as batch_op:
        batch_op.drop_index('ix_sp_company_year_code')
        batch_op.drop_index(batch_op.f('ix_sp_balances_product_code'))
        batch_op.drop_index(batch_op.f('ix_sp_balances_period_year'))
        batch_op.drop_index(batch_op.f('ix_sp_balances_company_id'))

    op.drop_table('sp_balances')
    with op.batch_alter_table('nvl_balances', schema=None) as batch_op:
        batch_op.drop_index('ix_nvl_company_year_code')
        batch_op.drop_index(batch_op.f('ix_nvl_balances_period_year'))
        batch_op.drop_index(batch_op.f('ix_nvl_balances_material_code'))
        batch_op.drop_index(batch_op.f('ix_nvl_balances_company_id'))

    op.drop_table('nvl_balances')
    with op.batch_alter_table('norms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_norms_product_code'))
        batch_op.drop_index(batch_op.f('ix_norms_period_year'))
        batch_op.drop_index(batch_op.f('ix_norms_material_code'))
        batch_op.drop_index(batch_op.f('ix_norms_company_id'))
        batch_op.drop_index('ix_norm_company_year_pair')

    op.drop_table('norms')
    with op.batch_alter_table('declaration_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_declaration_lines_period_year'))
        batch_op.drop_index(batch_op.f('ix_declaration_lines_item_code'))
        batch_op.drop_index(batch_op.f('ix_declaration_lines_hs_code'))
        batch_op.drop_index(batch_op.f('ix_declaration_lines_declaration_no'))
        batch_op.drop_index(batch_op.f('ix_declaration_lines_declaration_date'))
        batch_op.drop_index(batch_op.f('ix_declaration_lines_customs_code'))
        batch_op.drop_index(batch_op.f('ix_declaration_lines_company_id'))
        batch_op.drop_index('ix_decl_customs')
        batch_op.drop_index('ix_decl_company_year_code')

    op.drop_table('declaration_lines')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_tax_id'))
        batch_op.drop_index(batch_op.f('ix_companies_code'))

    op.drop_table('companies')
    # ### end Alembic commands ###
